language: java
dist: xenial

services:
  - docker

branches:
  only:
    - master

install:
  - set -e
  - nohup docker pull localstack/localstack-light > /dev/null &
  - nohup docker pull lambci/lambda:java8 > /dev/null &

script:
  - set -e
  - nohup docker pull localstack/localstack > /dev/null &
  - make compile
  - MVN_TEST_ARGS="-q -DskipTests" make test
  - make test
  - docker ps -a

notifications:
  email: false
