name: CI Build

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "8"
      - name: Pull Docker containers
        run: |
          set -e
          nohup docker pull localstack/localstack-light > /dev/null &
          nohup docker pull lambci/lambda:java8 > /dev/null &
          nohup docker pull localstack/localstack > /dev/null &
      - name: Compile Tests
        run: |
          set -e
          make compile
          MVN_TEST_ARGS="-q -DskipTests" make test
      - name: Thundra Maven Test Instrumentation Action
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: thundra-io/thundra-maven-test-action@v1
        with:
          apikey: ${{ secrets.THUNDRA_DEMO_ACCOUNT_LOCALSTACK_APIKEY }}
          project_id: ${{ secrets.THUNDRA_DEMO_ACCOUNT_LOCALSTACK_PROJECTID }}
      - name: Run Tests
        run: make test
        env:
          THUNDRA_AGENT_REPORT_REST_BASEURL: https://collector.thundra.us/v1
